type: EiffelTower_NoIMU
name: EiffelTower2020
args:
  root: D:\Datasets\EiffelTower\2020
  # Controls optional data sources
  gtDepth: false
  gtFlow: false
  gtPose: true
  window_length: 1
  is_stereo: false
  compressed: true
