type: EiffelTower_NoIMU
name: EiffelTower2020
args:
  root: D:\Datasets\EiffelTower\2020
  # Controls optional data sources
  gtDepth: false
  gtFlow: false
  gtPose: true
  is_stereo: false
  window_length: 1
  step_size: 1
  compressed: true
