import argparse
import time
import torch
import rerun as rr
import numpy as np
import pypose as pp
from pathlib import Path
from typing import List

from DataLoader import SequenceBase, Frame, smart_transform
from Evaluation.EvalSeq import EvaluateSequences
from Odometry.MACVO import MACVO

from Utility.Config import load_config, asNamespace
from Utility.PrettyPrint import print_as_table, ColoredTqdm, Logger
from Utility.Sandbox import Sandbox
from Utility.Visualize import fig_plt, rr_plt
from Utility.Timer import Timer
from Utility.read_eiva_vslam_outputs import load_vslam_track

def VisualizeRerunCallback(frame: Frame, system: MACVO, pb: ColoredTqdm, gt: List[torch.Tensor] | None = None):
    rr.set_time("frame_idx", sequence=frame.frame_idx)

    # Non-key frame does not need visualization
    if system.graph.frames.data["need_interp"][-1]: return

    if frame.frame_idx > 0:
        rr_plt.log_trajectory("/world/est", pp.SE3(system.graph.frames.data["pose"].tensor))

    # if gt is not None:
    #     gt = torch.stack(gt)
    #     gt = pp.SE3(gt)
    #     rr_plt.log_trajectory("/world/gt" , gt)

    if gt is not None:
        gt = pp.SE3(torch.stack(gt))  # (N,7) typically

        T_rot = gt[0].Inv()

        R = pp.euler2SO3(torch.tensor([-np.pi/2, 0., 0.], device=gt.device, dtype=gt.dtype))

        # Build SE3 with zero translation + rotation R
        batch = gt.shape[:-1]  # e.g. (N,)
        t0 = torch.zeros(*batch, 3, device=gt.device, dtype=gt.dtype)
        q  = R.tensor().expand(*batch, 4)  # quaternion part from SO3
        T_rot = pp.SE3(torch.cat([t0, q], dim=-1))

        gt = T_rot @ gt   # left-multiply: rotate in /world
        rr_plt.log_trajectory("/world/gt", gt)

    rr_plt.log_camera("/world/macvo/cam_left", pp.SE3(system.graph.frames.data["pose"][-1]), system.graph.frames.data["K"][-1])
    rr_plt.log_image ("/world/macvo/cam_left/rgb", frame.camera.imageL[0].permute(1, 2, 0))
    match_obs = system.graph.get_frame2match(system.graph.frames[-1:])
    rr_plt.log_keypoints("/world/macvo/cam_left/kpts", match_obs)

    map_points = system.graph.get_frame2map(system.graph.frames[-1:])
    rr_plt.log_points("/world/point_cloud_incremental", map_points.data["pos_Tw"].detach(), map_points.data["color"].detach(), map_points.data["cov_Tw"].detach(), "sphere")

    map_points = system.graph.get_frame2map(system.graph.frames[:])
    rr_plt.log_points("/world/point_cloud_all", map_points.data["pos_Tw"].detach(), map_points.data["color"].detach(), map_points.data["cov_Tw"].detach(), "sphere")

    vo_points  = system.graph.get_match2point(system.graph.get_frame2match(system.graph.frames[-1:]))
    rr_plt.log_points("/world/vo_tracking", vo_points.data["pos_Tw"].detach(), vo_points.data["color"].detach(), vo_points.data["cov_Tw"].detach(), "sphere")


def VisualizeVRAMUsage(frame: Frame, system: MACVO, pb: ColoredTqdm, iter_ms: float | None = None) -> float | None:
    if torch.cuda.is_available():
        reserved_gb  = torch.cuda.memory_reserved(0)  / 1e9
        allocated_gb = torch.cuda.memory_allocated(0) / 1e9
        vram_gb  = allocated_gb
        vram_str = f"{allocated_gb:.2f}/{reserved_gb:.2f} GB (alloc/reserved)"
    else:
        vram_gb = None
        vram_str = "N/A"

    fps_str = f", FPS={1000.0 / iter_ms:.1f}" if (iter_ms is not None and iter_ms > 0) else ""
    pb.set_description(desc=f"{system.graph}, VRAM={vram_str}{fps_str}")
    return vram_gb


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--odom", type=str, default = "Config/Experiment/MACVO/MACVO.yaml")
    parser.add_argument("--data", type=str, default = "Config/Sequence/TartanAir_abandonfac_001.yaml")
    parser.add_argument(
        "--seq_to",
        type=int,
        default=None,
        help="Crop sequence to frame# when ran. Set to -1 (default) if wish to run whole sequence",
    )
    parser.add_argument(
        "--seq_from",
        type=int,
        default=0,
        help="Crop sequence from frame# when ran. Set to 0 (default) if wish to start from first frame",
    )
    parser.add_argument(
        "--resultRoot",
        type=str,
        default="./Results",
        help="Directory to store trajectory and files generated by the script."
    )
    parser.add_argument(
        "--useRR",
        action="store_true",
        help="Activate RerunVisualizer to generate <config.Project>.rrd file for visualization.",
    )
    parser.add_argument(
        "--saveplt",
        action="store_true",
        help="Activate PLTVisualizer to generate <frame_idx>.jpg file in space folder for covariance visualization.",
    )
    parser.add_argument(
        "--preload",
        action="store_true",
        help="Preload entire trajectory into RAM to reduce data fetching overhead during runtime."
    )
    parser.add_argument(
        "--autoremove",
        action="store_true",
        help="Cleanup result sandbox after script finishs / crashed. Helpful during testing & debugging."
    )
    parser.add_argument(
        "--noeval",
        action="store_true",
        help="Evaluate sequence after running odometry."
    )
    parser.add_argument(
        "--timing",
        action="store_true",
        help="Record timing for system (active Utility.Timer for global time recording)"
    )
    parser.add_argument(
        "--vlsam",
        type=str,
        default=None,
        help="Path to VSLAM track txt file for visualization in Rerun."
    )
    parser.add_argument(
        "--n_to_align",
        type=int,
        default=-1,
        help="Number of poses used for trajectory alignment during evaluation (-1 = all)."
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = get_args()

    # Metadata setup & visualizer setup
    cfg, cfg_dict = load_config(Path(args.odom))
    odomcfg, odomcfg_dict = cfg.Odometry, cfg_dict["Odometry"]
    datacfg, datacfg_dict = load_config(Path(args.data))
    project_name = odomcfg.name + "@" + datacfg.name

    exp_space = Sandbox.create(Path(args.resultRoot), project_name)
    if args.autoremove: exp_space.set_autoremove()
    exp_space.config = {
        "Project": project_name,
        "Odometry": odomcfg_dict,
        "Data": {"args": datacfg_dict, "end_idx": args.seq_to, "start_idx": args.seq_from},
    }

    # Setup logging and visualization
    if args.useRR:
        rr_plt.default_mode = "rerun"
        rr_plt.init_connect(project_name)

    if hasattr(datacfg.args, "vslam") and datacfg.args.vslam:
        vslam_track = load_vslam_track(datacfg.args.vslam, entity_name=project_name)

    Timer.setup(active=args.timing)
    fig_plt.default_mode = "image" if args.saveplt else "none"

    _perf_last_t: list[float] = [time.monotonic()]
    _perf_iter_ms: list[float] = []
    _perf_vram_gb: list[float] = []

    def onFrameFinished(frame: Frame, system: MACVO, pb: ColoredTqdm, gt: List[torch.Tensor] | None = None):
        now = time.monotonic()
        iter_ms = (now - _perf_last_t[0]) * 1000.0
        _perf_last_t[0] = now
        if frame.frame_idx > 0:
            _perf_iter_ms.append(iter_ms)

        VisualizeRerunCallback(frame, system, pb, gt)
        vram_gb = VisualizeVRAMUsage(frame, system, pb, iter_ms if frame.frame_idx > 0 else None)
        if vram_gb is not None:
            _perf_vram_gb.append(vram_gb)

    # Initialize data source
    sequence = smart_transform(
        SequenceBase[Frame].instantiate(datacfg.type, datacfg.args).clip(args.seq_from, args.seq_to),
        cfg.Preprocess
    )

    if args.preload:
        sequence = sequence.preload()

    system = MACVO[Frame].from_config(asNamespace(exp_space.config))
    system.receive_frames(sequence, exp_space, on_frame_finished=onFrameFinished)

    if _perf_iter_ms:
        np.save(exp_space.path("iter_time_ms.npy"), np.array(_perf_iter_ms))
    if _perf_vram_gb:
        np.save(exp_space.path("vram_usage_gb.npy"), np.array(_perf_vram_gb))

    rr_plt.log_trajectory("/world/est"  , torch.tensor(np.load(exp_space.path("poses.npy"))[:, 1:]))
    try:
        rr_plt.log_points    ("/world/point_cloud",
                                system.get_map().map_points.data["pos_Tw"].tensor,
                                system.get_map().map_points.data["color"].tensor,
                                system.get_map().map_points.data["cov_Tw"].tensor,
                                "color")
    except RuntimeError:
        Logger.write("warn", "Unable to log full point cloud - is mapping mode on?")

    Timer.report()
    Timer.save_elapsed(exp_space.path("elapsed_time.json"))

    if args.useRR:
        rr.save(exp_space.path(f"{project_name}.rrd"))

    if not args.noeval:
        header, result = EvaluateSequences([str(exp_space.folder)], align=True, correct_scale=True ,align_origin=False, n_to_align=args.n_to_align)
        print_as_table(header, result)
