type: TartanAir_NoIMU
name: abf001
args:
  root: D:\Datasets\TartanAir_Sample\abandonedfactory_sample_P001\P001
  # Controls optional data sources
  gtDepth: true
  gtFlow: true
  gtPose: true
  is_stereo: false
  window_length: 2

  compressed: false
