type: TartanAir_NoIMU
name: soulcity
args:
  root: D:\Datasets\TartanAir_Sample\soulcity_sample_P003\P003
  # Controls optional data sources
  gtDepth: false
  gtFlow: true
  gtPose: true

  compressed: false
