type: TartanAir_NoIMU
name: japanese
args:
  root: D:\Datasets\TartanAir_Sample\japanesealley_sample_P007\P007
  # Controls optional data sources
  gtDepth: false
  gtFlow: true
  gtPose: true

  compressed: false
