type: TartanAir_NoIMU
name: gascola
args:
  root: D:\Datasets\TartanAir_Sample\hospital_sample_P000\P000
  # Controls optional data sources
  gtDepth: false
  gtFlow: true
  gtPose: true

  compressed: false
