-   type: TartanAir_NoIMU
    name: abandonedfactory_E001
    args:
        root: D:\Datasets\TartanAir_Sample\abandonedfactory_sample_P001\P001
        compressed: true
        gtDepth: false
        gtPose: true
        gtFlow: true
