- type: EIVA_NoIMU
  name: EIVA_plane_nose
  args:
    root: D:\Datasets\EIVA\plane_nose
    # Controls optional data sources
    gtDepth: false
    gtFlow: false
    gtPose: true
    is_stereo: false
    window_length: 1
    step_size: 1
    navigation_names: [plane_nose]
    sequence_camera_names: [left, right]
    compressed: true

- type: EIVA_NoIMU
  name: EIVA_plane_mid
  args:
    root: D:\Datasets\EIVA\plane_mid
    # Controls optional data sources
    gtDepth: false
    gtFlow: false
    gtPose: true
    is_stereo: false
    window_length: 1
    navigation_names: [plane_mid]
    sequence_camera_names: [left, right]
    compressed: true

- type: EIVA_NoIMU
  name: EIVA_plane_tail1
  args:
    root: D:\Datasets\EIVA\Voyis\plane_tail1
    # Controls optional data sources
    gtDepth: false
    gtFlow: false
    gtPose: true
    window_length: 1
    is_stereo: false
    compressed: true

- type: EIVA_NoIMU
  name: EIVA_plane_tail2
  args:
    root: D:\Datasets\EIVA\Voyis\plane_tail2
    # Controls optional data sources
    gtDepth: false
    gtFlow: false
    gtPose: true
    window_length: 1
    is_stereo: false
    compressed: true


- type: EIVA_NoIMU
  name: EIVA_long_ladder
  args:
    root: D:\Datasets\EIVA\Voyis\long_ladder_scan
    # Controls optional data sources
    gtDepth: false
    gtFlow: false
    gtPose: true
    window_length: 1
    is_stereo: false
    compressed: true

- type: EIVA_NoIMU
  name: EIVA_OREC_CPS
  args:
    root: D:\Datasets\EIVA\OREC_CPS
    # Controls optional data sources
    gtDepth: false
    gtFlow: false
    gtPose: true
    window_length: 1
    is_stereo: false
    compressed: true

- type: EIVA_NoIMU
  name: EIVA_Welland_test_first_dive
  args:
    root: D:\Datasets\EIVA\Voyis\Welland_test_first_dive
    # Controls optional data sources
    gtDepth: false
    gtFlow: false
    gtPose: true
    window_length: 1
    is_stereo: false
    compressed: true
