type: EIVA_NoIMU
name: plane_nose
args:
  root: D:\Datasets\EIVA\plane_nose
  # Controls optional data sources
  gtDepth: false
  gtFlow: false
  gtPose: true
  is_stereo: false
  navigation_names: [plane_nose]
  sequence_camera_names: [left, right]

  compressed: true
