type: EIVA_NoIMU
name: plane_tail2
args:
  root: D:\Datasets\EIVA\Voyis\plane_tail2
  # Controls optional data sources
  gtDepth: false
  gtFlow: false
  gtPose: true
  is_stereo: true

  compressed: true
