type: EIVA_StereoSequenceORM
name: abf001
args:
  root: D:\Datasets\mac-vio\plane_nose
  # Controls optional data sources
  gtDepth: false
  gtFlow: false
  gtPose: true
  navigation_names: [plane_nose]
  sequence_camera_names: [left, right]

  compressed: true
