type: EIVA_NoIMU
name: plane_mid
args:
  root: D:\Datasets\EIVA\plane_mid
  # Controls optional data sources
  gtDepth: false
  gtFlow: false
  gtPose: true
  window_length: 2
  is_stereo: false
  navigation_names: [plane_mid]
  sequence_camera_names: [left, right]

  compressed: true
