type: EIVA_NoIMU
name: fishfarm_20260202T064248
args:
  root: X:\DataSets\EIVACollectedData\SLAM\260129 JM x Voyis\Day 5 - Fish Farm 1\P3000 - Fish Farm Net\vSLAMCache\Run_20260202T064248\180199A003output
  # Controls optional data sources
  gtDepth: false
  gtFlow: false
  gtPose: false
  is_stereo: true
  window_length: 1 # 1 with dav2, N with dav3
  compressed: true
